// swift-tools-version:5.9
// Termoak Swift package for iOS.
//
// Before using it, build the Rust library and create the xcframework on a Mac
// with Xcode: `scripts/build-ios.sh` (see docs/MOBILE.md).
// The app imports `TermoakKit`, which re-exports the generated API.
import PackageDescription

let package = Package(
    name: "TermoakKit",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "TermoakKit", targets: ["TermoakKit"]),
    ],
    targets: [
        // Rust library (static) + C header, created by scripts/build-ios.sh.
        .binaryTarget(
            name: "termoak_ffiFFI",
            path: "termoak_ffiFFI.xcframework"
        ),
        // Swift API generated by UniFFI. Do not edit: scripts/generate-bindings.sh.
        .target(
            name: "TermoakFFI",
            dependencies: ["termoak_ffiFFI"],
            path: "Sources/TermoakFFI",
            exclude: ["termoak_ffiFFI.h", "termoak_ffiFFI.modulemap"]
        ),
        // Hand-written helpers on top of the generated API.
        .target(
            name: "TermoakKit",
            dependencies: ["TermoakFFI"],
            path: "Sources/TermoakKit"
        ),
    ]
)
