// Hand-written helpers on top of the API generated by UniFFI.
// The app only needs `import TermoakKit`: it re-exports `TermoakFFI`.

@_exported import TermoakFFI
import Foundation

public extension TermoakError {
    /// Message ready to show to the user (the Rust core writes it in English).
    ///
    /// Every variant carries only the message; it is extracted without
    /// listing them, so this does not need touching when variants are added.
    var message: String {
        if let payload = Mirror(reflecting: self).children.first?.value {
            if let text = payload as? String {
                return text
            }
            if let text = Mirror(reflecting: payload).children.first?.value as? String {
                return text
            }
        }
        return String(describing: self)
    }
}

/// Readable message of any error (Termoak errors use their own message).
public func errorMessage(_ error: Error) -> String {
    (error as? TermoakError)?.message ?? error.localizedDescription
}
